version: 2.1

# ====================
# WORKFLOW DECLARATION
# ====================
workflows:
  version: 2
  main:
    jobs:
      - install_dependencies
      - build:
          requires:
            - install_dependencies
      - lint:
          requires:
            - install_dependencies
      - test:
          requires:
            - install_dependencies
      # - cypress_job:
      #     requires:
      #       - install_dependencies
      - semantic_release:
          requires:
            - build
            - lint
            - test
          filters:
            branches:
              only:
                - master
      # - sentry_release:
      #     requires:
      #       - semantic_release
      #     filters:
      #       branches:
      #         only:
      #           - master

# ===================
# Shared definitions.
# ===================
defaults: &defaults
  working_directory: /root/multiar.ch
  docker:
    - image: node:12

# ====================
# SHARED JOBS POINTERS
# ====================
save_cache: &save_cache
  save_cache:
    paths:
      - /root/multiar.ch/node_modules/
      - /root/.cache/yarn/
    key: v5-dependencies-{{ checksum "yarn.lock" }}

restore_cache: &restore_cache
  restore_cache:
    keys:
      - v5-dependencies-{{ checksum "yarn.lock" }}
      - v5-dependencies-

restore_public_dir_cache: &restore_public_dir_cache
  restore_cache:
    keys:
      - v2-public-dir-{{ .Branch }}-{{ .Revision }}
      - v2-public-dir-{{ .Branch }}
      - v2-public-dir-

save_public_dir_cache: &save_public_dir_cache
  save_cache:
    paths:
      - public/
    key: v2-public-dir-{{ .Branch }}-{{ .Revision }}

install_dependencies: &install_dependencies
  run:
    name: Install dependencies.
    command: yarn --silent --no-progress --frozen-lockfile

semantic_release: &semantic_release
  <<: *defaults
  steps:
    - checkout
    - *restore_cache
    - run: yarn semantic-release

sentry_release: &sentry_release
  <<: *defaults
  steps:
    - checkout
    - *restore_cache
    - run: curl -sL https://sentry.io/get-cli/ | bash
    - run: sh ./scripts/update-sentry-release.sh

# cypress_job: &cypress_job
#   working_directory: ~/multiar.ch
#   docker:
#     # the Docker image with Cypress dependencies
#     - image: cypress/base:12.6.0
#       environment:
#         ## this enables colors in the output
#         TERM: xterm
#   steps:
#     - checkout
#     - *restore_cache
#     - *load_aws_credentials
#     - run:
#         command: GATSBY_ENV=Staging yarn gatsby develop
#         background: true
#     - run: sleep 60s
#     - run: yarn cypress install
#     - run: yarn cypress run

# ================
# JOB DECLARATIONS
# ================
jobs:
  install_dependencies:
    <<: *defaults
    steps:
      - checkout
      - *restore_cache
      - *install_dependencies
      - *save_cache

  lint:
    <<: *defaults
    steps:
      - checkout
      - *restore_cache
      - run:
          name: Run linter.
          command: yarn lint

  test:
    <<: *defaults
    steps:
      - checkout
      - *restore_cache
      - run:
          name: Run Jest tests & collect coverage.
          command: |
            yarn jest --coverage --runInBand --ci
          environment:
            JEST_JUNIT_OUTPUT: 'reports/junit/js-test-results.xml'
      - store_test_results:
          path: reports/junit
      - store_artifacts:
          path: reports/junit
      - run:
          name: Upload results to Codecov.
          command: yarn codecov

  build:
    <<: *defaults
    steps:
      - checkout
      - *restore_cache
      - *restore_public_dir_cache
      - run:
          name: Build static site. (with limited assets)
          command: yarn build
      - *save_cache
      - *save_public_dir_cache

  # ---------------------------------------------------------------------------

  semantic_release: *semantic_release

  sentry_release: *sentry_release
